- name: play-01
  hosts: web
  tasks:
  - name: task-01 play-01
    ansible.builtin.debug:
      msg: "this is from task 01 and play 01"

- name: paly-02
  hosts: web 
  tasks:
  - name: task-01 play-02
    ansible.builtin.debug:
      msg: "this is from task 01 and play 02"


      
      
#ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 02.multi-play.yaml



# PLAY [play-01] ***********************************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.47.221]

# TASK [task-01 play-01] ***************************************************************************************************************
# ok: [172.31.47.221] => {
#     "msg": "this is from task 01 and play 01"
# }

# PLAY [paly-02] ***********************************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.47.221]

# TASK [task-01 play-02] ***************************************************************************************************************
# ok: [172.31.47.221] => {
#     "msg": "this is from task 01 and play 02"
# }

# PLAY RECAP ***************************************************************************************************************************
# 172.31.47.221              : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


