- name: installing and running nginx
  hosts: web
  become: yes
  tasks:
  - name: installing nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: run nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


# ansible-playbook -i inventory.ini -e ansible_user=ec2-user -e ansible_password=DevOps321 03.nginx.yaml

# PLAY [installing and running nginx] **************************************************************************************************

# TASK [Gathering Facts] ***************************************************************************************************************
# ok: [172.31.47.221]

# TASK [installing nginx] **************************************************************************************************************
# ok: [172.31.47.221]

# TASK [run nginx] *********************************************************************************************************************
# ok: [172.31.47.221]

# PLAY RECAP ***************************************************************************************************************************
# 172.31.47.221              : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0


