- name: variables
  hosts: web
  vars:
    course: "Devops with AWS"
    duration: "120 hrs"
  tasks: 
  - name: printing variables
    ansible.builtin.debug:
      msg: "Hi, ia m learning {{course}} {{duration}}"