- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: printing the information
    ansible.builtin.debug:
      msg: "i am learning : {{COURSE}}, duration : {{DURATION}}"
      