- name: variables from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: printing course information
    ansible.builtin.debug:
      msg: "i am learning : {{course}}, duration : {{duration}}"