- name: variables from files
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter course name
  - name: DURATION
    prompt: please enter time duration
  tasks:
  - name: printing the information
    ansible.builtin.debug:
      msg: "i am learning : {{COURSE}}, duration : {{DURATION}}"