- name: conditions
  hosts: local
  connection: local   #use this statement because we are not providing usernma eand password
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print if given number is greater than 20
    ansible.builtin.debug:
      msg: "given number is greater than 20"
    when: number | > 20
  