- name: conditions
  hosts: web
  connection: local   #use this statement because we are not providing usernma eand password
  vars:
    number: 25
  tasks:
  - name: print this statement if given number is greater than or equal to 20
    ansible.builtin.debug:
      msg: "given number is greater than 20"
    when: number | int >= 20

  - name: print this statement if given number is less than 20
    ansible.builtin.debug:
      msg: "given number is less than 20"
    when: number | int < 20
  