- name: conditions to create user
  hosts: web
  tasks:
  - name: creating user
    ansible.builtin.command: id expense
    register: USER  #user is a variable that gets o/p from above command

  - name: print user information
    ansible.builtin.debug:
     msg: "user info is: {{name}}, {{password}}"