- name: filters or functions
  hosts: web
  connection: local
  tasks: 
  - name: declaring default variable
    ansible.builtin.debug:
      msg: "Learning {{ course | default('Ansible') }}"


# TASK [declaring default variable] ****************************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": "Learning Ansible"


  - name: converting lower case to upper case
    vars: 
      greetings: "Hello Vijaya"
    ansible.builtin.debug:
      msg: " {{ greetings | upper }}"

  - name: converting upper case to lower case
    vars:
      greetings: "hello vijaya"
    ansible.builtin.debug:
      msg: " {{ greetings | lower }}"


# TASK [converting lower case to upper case] *******************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": " HELLO VIJAYA"
# }

# TASK [converting upper case to lower case] *******************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": " hello vijaya"
# }

  - name: unique numbers
    vars: 
      numbers: [1,2,3,4,5,4,3,2,1]
    ansible.builtin.debug:
      msg: " {{ numbers | unique }}"


# TASK [unique numbers] ****************************************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": " [1, 2, 3, 4, 5]"


  - name: to get min and max numbers
    vars:
      numbers: [1,23,34,45,56,67]
    ansible.builtin.debug:
      msg: " Min: {{ numbers | min }}, Max: {{ numbers | max}}"

# TASK [to get min and max numbers] ****************************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": " Min: 1, Max: 67"

  - name: convert map to lost
    vars:
      course:
        name: "Devops with AWS"
        duration: 120
    ansible.builtin.debug:
      msg: "{{ course | dict2items}}"

# TASK [convert map to lost] ***********************************************************************************************************
# ok: [172.31.38.167] => {
#     "msg": [
#         {
#             "key": "name",
#             "value": "Devops with AWS"
#         },
#         {
#             "key": "duration",
#             "value": 120
#         }
#     ]
# }


  - name: convert list to map
    vars: 
      course:
      -  { "key": "name", "value": "Devops with AWS" },
      -  { "key": "duration", "value": 120 }        
    ansible.builtin.debug:
      msg: "{{ course | dict2list }}"
    


